yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path('create/', views.post_create, name='post_create'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler403 = 'core.views.forbidden'
handler500 = 'core.views.page_500_found'
handler404 = 'core.views.page_not_found'
CSRF_FAILURE_VIEW = 'core.views.csrf_failure'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about'))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'


class Post(CreatedModel):
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='posts_group',
        help_text='Группа к которой будет относиться пост',
        verbose_name='Группа',
    )
    text = models.TextField(
        verbose_name='text',
        help_text='Текст нового поста'
    )
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name='posts',
        verbose_name='Автор',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Comment(models.Model):
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        related_name='comments',
        on_delete=models.CASCADE,
    )
    text = models.TextField(
        verbose_name='Комментарий',
        help_text='Текст комментария'
    )
    created = models.DateTimeField(
        'Отправлено в:',
        auto_now_add=True,
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        verbose_name='Подписчик',
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        verbose_name='Автор',
        on_delete=models.CASCADE,
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = [
            models.UniqueConstraint(
                name="%(app_label)s_%(class)s_name_unique",
                fields=['author'],
            ),
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpRequest
from django.shortcuts import get_object_or_404, redirect, render

from posts.forms import CommentForm, PostForm
from posts.models import Follow, Group, Post, User

ORDER_SORT = 10


def index(request: HttpRequest) -> HttpRequest:
    """View функция главной страницы."""
    posts = Post.objects.select_related('group')
    paginator = Paginator(posts, ORDER_SORT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    title = 'Последние обновления на сайте'
    context = {
        'page_obj': page_obj,
        'posts': posts,
        'title': title,
    }
    template = 'posts/index.html'
    return render(request, template, context)


def group_posts(request: HttpRequest, slug: str) -> HttpRequest:
    """View функция для страницы с постами по группам."""
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group)
    paginator = Paginator(posts, ORDER_SORT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    title = 'Лев Толстой – зеркало русской революции.'
    context = {
        'title': title,
        'group': group,
        'posts': posts,
        'page_obj': page_obj,
    }
    template = 'posts/group_list.html'
    return render(request, template, context)


def profile(request: HttpRequest, username: str) -> HttpRequest:
    """View функция для страницы профиля пользователя."""
    author = get_object_or_404(User, username=username)
    user = request.user
    following = False
    posts = author.posts.all()
    posts_count = author.posts.count()
    paginator = Paginator(posts, ORDER_SORT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    if user.is_authenticated:
        following = Follow.objects.filter(user=user, author=author).exists()
    context = {
        'author': author,
        'posts_count': posts_count,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request: HttpRequest, post_id: int) -> HttpRequest:
    """View функция для страницы отдельного поста пользователя."""
    post = get_object_or_404(Post, id=post_id)
    group = post.group
    author = post.author
    posts_count = author.posts.count()
    comments = post.comments.select_related('author')
    form = CommentForm()
    context = {
        'post': post,
        'group': group,
        'posts_count': posts_count,
        'comments': comments,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """View функция создания нового поста."""
    template = 'posts/post_create.html'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.pub_date = datetime
        post.save()
        return redirect('posts:profile', request.user)
    return render(request, template, {'form': form})


@login_required
def post_edit(request, post_id):
    """View функция редактирования поста."""
    template = 'posts/post_create.html'
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    if not form.is_valid():
        return render(request, template, {'form': form})
    form.save()
    return redirect('posts:post_detail', post_id)


@login_required
def add_comment(request, post_id):
    """View функция добавления комментария."""
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """View функция страницы подписок."""
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, ORDER_SORT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """View функция кнопки подписаться."""
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    """View функция кнопки отписаться."""
    author = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(
        user=request.user,
        author=author
    )
    follow.delete()
    return redirect('posts:profile', username=author)

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{%block title %}Мои подписки
{%endblock title%}
{% load cache %}
{% block content %}
  <h1>Мои подписки</h1>
  {% include 'posts/includes/switcher.html' %}
  <article>
    {% for post in page_obj %}
    <ul>
      <li>
        Автор:
        <a href="{% url 'posts:profile' post.author.username %}">
          {{ post.author.get_full_name }}
        </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:'d E Y' }}
      </li>
    </ul>
    <p>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      {{ post.text }}
    </p>
    {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы{{ group.description }}</a>
    {% endif %}
  </article>
  {% if not forloop.last %}
  <hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{%endblock%}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}{{ group }}
{% endblock %}
{% block content %}
<h1>{{ group.title }}</h1>
<p>
  {{ group.description }}
</p>
<article>
  {% for post in page_obj %}
  <ul>
    <li>
      Автор:
      <a href="{% url 'posts:profile' post.author.username %}">
        {{ post.author.get_full_name }}
      </a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:'d E Y' }}
    </li>
  </ul>
  <p>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    {{ post.text|linebreaksbr }}
  </p>
</article>
{% if not forloop.last %}
<hr>{% endif %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{%endblock%}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{%block title %}{{ title }}
{%endblock title%}
{% load cache %}
{% block content %}
  <h1>{{ title }}</h1>
  {% include 'posts/includes/switcher.html' %}
  <article>
    {% cache 20 index_page page_obj.number %}
    {% for post in page_obj %}
    <ul>
      <li>
        Автор:
        <a href="{% url 'posts:profile' post.author.username %}">
          {{ post.author.get_full_name }}
        </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:'d E Y' }}
      </li>
    </ul>
    <p>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      {{ post.text|linebreaksbr }}
    </p>
    {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы{{ group.description }}</a>
    {% endif %}
  </article>
  {% if not forloop.last %}
  <hr>{% endif %}
  {% endfor %}
  {%endcache%}
  {% include 'posts/includes/paginator.html' %}
{%endblock%}

yatube/templates/posts/post_create.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %}
Редактировать пост
{% else %}
Новый пост
{% endif %}
{% endblock %}
{% block content %}
<main>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
            Редактировать пост
            {% else %}
            Новый пост
            {% endif %}
          </div>
          {%load user_filters%}
          <div class="card-body">
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_text">
                  Текст поста
                  <span class="required text-danger">*</span>
                </label>
                {{ form.text|addclass:'form-control' }}
                <small id="id_text-help" class="form-text text-muted">
                  Текст нового поста
                </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_group">
                  Выберите группу:
                </label>
                {{ form.group|addclass:'form-control' }}
                <small id="id_group-help" class="form-text text-muted">
                  Группа, к которой будет относиться пост
                </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_image">
                  Картинка
                  {{ form.image|addclass:'form-control' }}
                </label>
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                  Сохранить
                  {% else %}
                  Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{%block title %}
{{ post|slice:30 }}
{%endblock%}
{%block content%}
  {%load user_filters%}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:'d E Y' }}
        </li>
        {%if post.group %}
        <li class="list-group-item">
          Группа:
          <a href="{% url 'posts:group_list' post.group.slug %}">
            {{group.title}}
          </a>
        </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{post.author.get_full_name}}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span>{{posts_count}}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        {{ post.text|linebreaksbr }}
      </p>
      <p>
        {% if post.author == request.user %}
        <a href="{% url 'posts:post_edit' post.id %}" class="btn btn-primary">Редактировать запись</a>
        {% endif %}
        {% include 'includes/comments.html' %}
      </p>
    </article>
  </div>
{%endblock%}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{%block title %}Профайл пользователя {{User.username}}
{%endblock%}
{%block content%}
<div class="mb-5">
  <h1>Все посты пользователя {{ author.get_full_name }}</h1>
  <h3>Всего постов: {{ posts_count }}</h3>
  {% if request.user != author %}
    {% if following %}
    <a class="btn btn-lg btn-light" href="{% url 'posts:profile_unfollow' author.username %}" role="button">
      Отписаться
    </a>
    {% else %}
    <a class="btn btn-lg btn-primary" href="{% url 'posts:profile_follow' author.username %}" role="button">
      Подписаться
    </a>
    {% endif %}
  {% endif %}
</div>
<article>
  {%for post in page_obj%}
  <ul>
    <li>
      Автор: {{post.author.get_full_name}}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:'d E Y' }}
    </li>
  </ul>
  <p>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    {{ post.text|linebreaksbr }}
  </p>
  <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
  {% if not forloop.last %}
  <hr>{% endif %}
  {% endfor %}
</article>
{% include 'posts/includes/paginator.html'  %}
{%endblock%}